<br>

<button class="accordion" >Tata Cara Membayar Melalui ATM/ANT/SETAR-Setor Tarik</button>
<div class="panel">
    <b>Langkah-langkah transaksi BCA Virtual Account melalui ATM/ANT/SETAR-Setor Tarik:</b>
    <br>
    <ol>
        <li>Pilih menu Transfer – Ke Rek BCA Virtual Account</li>
        <li>Masukkan Nomor BCA Virtual Account, lalu pilih Benar</li>
        <li>Pilih menu “Ke Rek BCA Virtual Account”</li>
        <li>Layar ATM akan menampilkan konfirmasi transaksi:<br>
            <ul>
                <li>Pilih Ya bila setuju, atau </li>
                <li>Masukkan jumlah transfer, lalu pilih Benar. Layar ATM akan kembali menampilkan konfirmasi jumlah pembayaran, pilih Ya bila ingin membayar</li>
            </ul>
        </li>
        <li>Ikuti langkah selanjutnya sampai transaksi selesai</li>
    </ol>
</div>

<button class="accordion" >KlikBCA Individu (Full Site dan versi Smartphone)</button>
<div class="panel">
    <b>Langkah-langkah transaksi BCA Virtual Account melalui KlikBCA Individu: </b>
    <br>
    <ol>
        <li>Pilih Menu Transfer Dana – Transfer ke BCA Virtual Account</li>
        <li>Masukkan nomor BCA Virtual Account, atau pilih Dari Daftar Transfer </li>
        <li>Akan tampil konfirmasi transaksi: <br>
            <ul>
                <li>Masukkan jumlah nominal transfer dan berita, atau </li>
                <li>Masukkan berita</li>
            </ul>
        </li>
        <li>Ikuti langkah selanjutnya sampai transaksi selesai </li>
    </ol>
</div>

<button class="accordion" >KlikBCA Bisnis</button>
<div class="panel">
    <b>Langkah-langkah transaksi BCA Virtual Account melalui KlikBCA Bisnis: </b>
    <br>
    <ul>
        <li>Daftar Transfer: <br>
            <ol>
                <li>Pilih menu Daftar Transfer - Tambah, pilih Ke BCA Virtual Account</li>
                <li>Masukkan nomor BCA Virtual Account</li>
                <li>Ikuti langkah selanjutnya sampai selesai </li>
            </ol>
        </li>
        <li>Transfer Dana: <br>
            <ol>
                <li>Pilih menu Transfer Dana – ke BCA Virtual Account</li>
                <li>Pilih nomor rekening yang akan didebet dan pilih nomor BCA Virtual Account, lalu lanjut </li>
                <li>Akan tampil konfirmasi transaksi: <br>
                    <ul>
                        <li>Masukkan jumlah nominal transfer dan berita, atau</li>
                        <li>Masukkan berita</li>
                    </ul>
                </li>
                <li>Ikuti langkah selanjutnya sampai transaksi selesai</li>
            </ol>
        </li>
        <li>Otorisasi Transaksi: <br>
            <ul style="list-style-type:none">
                <li>Pilih menu Transfer Dana - Otorisasi Transaksi Tergantung single/multi otorisasi</li>
                <li>Untuk Single Otorisasi: <br>
                    <ul>
                        Login User Releaser
                        <li>Tandai transaksi pada tabel Transaksi Yang Belum Diotorisasi, pilih Setuju </li>
                        <li>Ikuti langkah selanjutnya sampai selesai</li>
                    </ul>
                </li>

                <li>Untuk Multi Otorisasi: <br>
                    <ul>
                        <li>Login User Approver
                            <ol>
                                <li>Tandai transaksi pada tabel Approver, pilih Setuju </li>
                            </ol>
                        </li>
                        <li>Login User Releaser
                            <ol>
                                <li>Tandai transaksi pada tabel Transaksi Yang Belum Diotorisasi, pilih Setuju</li>
                                <li>Ikuti langkah selanjutnya sampai selesai</li>
                            </ol>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>

<button class="accordion" >m-BCA (BCA Mobile)</button>
<div class="panel">
    <b>Langkah-langkah transaksi BCA Virtual Account melalui m-BCA (BCA Mobile):</b>
    <br>
    <ol>
        <li>Pilih m-Transfer</li>
        <li>Pilih Transfer – BCA Virtual Account</li>
        <li>Pilih nomor rekening yang akan didebet</li>
        <li>Masukkan nomor BCA Virtual Account, lalu pilih OK</li>
        <li>Tampil konfirmasi nomor BCA Virtual Account dan rekening pendebetan, lalu Kirim</li>
        <li>Tampil konfirmasi pembayaran, lalu pilih OK <br>
            <ul>
                <li>Masukkan jumlah nominal transfer dan berita, atau </li>
                <li>Masukkan berita</li>
            </ul>
        </li>
        <li>Ikuti langkah selanjutnya sampai transaksi selesai </li>
    </ol>
</div>

<button class="accordion" >m-BCA (STK)</button>
<div class="panel">
    <b>Langkah-langkah transaksi BCA Virtual Account melalui m-BCA (STK):</b>
    <br>
    <ol>
        <li>Pilih m-BCA </li>
        <li>Pilih m-Payment</li>
        <li>Pilih Lainnya</li>
        <li>Masukkan TVA pada Nama PT, lalu OK</li>
        <li>Masukkan nomor BCA Virtual Account pada No. Pelanggan, lalu OK</li>
        <li>Masukkan PIN m-BCA, lalu OK</li>
        <li>Pilih Pilih nomor rekening yang akan didebet, lalu lanjut</li>
        <li>Akan muncul konfirmasi pembayaran, lalu pilih OK <br>
            <ul>
                <li>Masukkan jumlah bayar dan berita, atau </li>
                <li>Masukkan berita</li>
            </ul>
        </li>
        <li>Ikuti langkah selanjutnya sampai transaksi selesai </li>
    </ol>
</div>




<script >
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>




