<br>

<button class="accordion" >Pembayaran Melalui ATM Danamon </button>
<div class="panel">
    <b>Pembayaran Melalui ATM Permata</b>
    <ol>
        <li>Masuk ke menu Pembayaran -> Lainnya -> Virtual Account </li>
        <li>Masukkan 16 digit nomor Virtual Account </li>
        <li>Periksa jumlah tagihan dan konfirmasi pembayaran. </li>
    </ol>
</div>

<button class="accordion" >Transfer dari Bank Lain </button>
<div class="panel">
    <ol>
        <li>Transfer melalui Bank Lain yang tergabung dalam jaringan ATM Bersama, ALTO dan Prima.</li>
        <li>Masukkan kode Bank Danamon (011) dan 16 digit nomor Virtual Account di rekening tujuan.</li>
        <li>Masukkan nominal transfer sesuai tagihan.</li>
    </ol>
</div>




<script >
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>




