<br>

<button class="accordion" >Tata Cara Membayar Melalui Indomaret</button>
<div class="panel">
    <ol>
        <li>Catat dan simpan kode pembayaran Indomaret anda, yaitu : <b><?php echo $faspayOrder->getTrxId()?></b></li>
        <li>Tunjukan kode pembayaran ke kasir Indomaret terdekat dan lakukan pembayaran senilai <b><?php echo $order->getBaseCurrencyCode()." ".number_format($order->getTotalDue()) ?></b></li>
        <li>Simpan bukti pembayaran yang sewaktu-waktu diperlukan jika terjadi kendala transaksi</li>
    </ol>
</div>




<script >
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>




