<br>

<button class="accordion" >Tata Cara Membayar Melalui ATM </button>
<div class="panel">
    <ol>
        <li>Catat kode pembayaran yang anda dapat</li>
        <li>Gunakan ATM Mandiri untuk menyelesaikan pembayaran</li>
        <li>Masukkan PIN anda</li>
        <li>Pilih 'Bayar/Beli' lalu pilih 'Lainnya'</li>
        <li>Cari pilihan MULTI PAYMENT</li>
        <li>Masukkan Kode Perusahaan <b><?php echo $data->getMerchantId()?></b></li>
        <li>Masukkan Kode Pelanggan <b><?php echo $faspayOrder->getTrxId() ?></b></li>
        <li>Pilih Tagihan Anda jika sudah sesuai tekan YA</li>
        <li>Konfirmasikan tagihan anda apakah sudah sesuai lalu tekan YA</li>
        <li>Harap Simpan Struk Transaksi yang anda dapatkan</li>
    </ol>
</div>

<button class="accordion" >Tata Cara Membayar Melalui Mandiri Internet Banking </button>
<div class="panel">
    <ol>
        <li>Pada Halaman Utama pilih submenu Lain-lain di bawah menu Pembayaran</li>
        <li>Cari Penyedia Jasa 70009 MitraPay</li>
        <li>Isi Nomor Pelanggan yang anda dapatkan</li>
        <li>Masukkan Jumlah Pembayaran sesuai dengan Jumlah Tagihan anda</li>
        <li>Pilih LANJUTKAN</li>
        <li>Transaksi selesai, jika perlu CETAK hasil transaksi anda</li>
    </ol>
</div>




<script >
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>




