<br>

<button class="accordion" >Pembayaran melalui ShopeePay</button>
<div class="panel">
    <ol>
        <li>Buka aplikasi Shopee</li>
        <li>Klik logo “Scan”</li>
        <li>Scan QR Code</li>
        <li>Klik tombol “Bayar Sekarang”</li>
    </ol>
</div>

<button class="accordion" >Pembayaran melalui Mobile Banking atau E-Money lainnya</button>
<div class="panel">
    <ol>
        <li>Buka aplikasi mobile banking atau e-money</li>
        <li>Klik logo “Pay” atau “Scan”</li>
        <li>Scan QR Code</li>
        <li>Klik tombol “Pay” atau “Bayar”</li>
    </ol>
</div>



<script >
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>




