<?php
    if(isset($_GET)){
        // $noslash = explode("/",$_GET['order_id']);
        $get = $_GET;
    ?>

<center>
    
    <div>
        <img src='<?php echo $this->getViewFileUrl('Faspay_Credit::images/asset/thank.jpg'); ?>' alt="Demo">
        <br>
        <br>
        <br>
    </div>

    <h3><?php echo $this->check($get); ?></h3>

    <meta http-equiv="refresh" content="60;url= <?php echo $block->getUrl('/') ?>" />


</center>


<?php }else{ ?>
        NO ORDER LISTED
<?php } ?>





